### ISSUE TITLE
system refuses connection If user tries to upload cv

### ISSUE THREAD

**Issue by NirpendraNathMishra** [githubstevemas/scrape-and-hire#2]
HI Dude coool Project 
The app keeps crashing if user tries to upload His new cv And Please add some feature for adding the model in English

**Comment by githubstevemas** [comment]
Thank you for your feedback! I will look for the uploading crash. 

What English model are you talking about? The model for spaCy?

**Comment by NirpendraNathMishra** [comment]
Yes Buddy 

Try This =https://spacy.io/models/en/
We can do something like when the app boots up we can ask user for English or French And Then We can use the model according to that

**Comment by githubstevemas** [comment]
Good idea, I'll add it to the todo list!

**Comment by githubstevemas** [comment]
Feature added! You can now install many models and set which one the process will use in the Settings menu.
